#!/bin/bash -e
cd openapi-specs

SPECS=$(ls *.yaml | grep -v PetStore.yaml)

echo -e "Available OpenAPI specs:\n"
echo -e "1. PetStore_Ver00.yaml"
echo -e "2. PetStore_Ver01+Food.yaml"
echo -e "\nType the number you want [1, 2] to apply and press ENTER:"
read SELECTION

if [ "x$SELECTION" == "x2" ]; then
    SELECTED="PetStore_Ver01+Food.yaml"
else
    SELECTED="PetStore_Ver00.yaml"
fi

echo -e "\nApplying $SELECTED ...\n"

cp -a "$SELECTED" PetStore.yaml

cd ..

./generate-client-sdk

SWIFT_FILES=$(grep -rl "FOOD ADDITIONS" . | grep ".swift" | uniq)

if [ "$SELECTED" == "PetStore_Ver01+Food.yaml" ]; then
    echo
    echo "Uncommenting FOOD ADDITIONS ..."
    for file in $SWIFT_FILES; do
        echo "Processing $file"
        sed -i.bak 's/\/\* FOOD ADDITIONS START/\/\* FOOD ADDITIONS START \*\//' $file
        sed -i.bak 's/FOOD ADDITIONS END \*\//\/\* FOOD ADDITIONS END \*\//' $file
    done
else
    echo
    echo "Commenting FOOD ADDITIONS ..."
    for file in $SWIFT_FILES; do
        echo "Processing $file"
        sed -i.bak 's/\/\* FOOD ADDITIONS START \*\//\/\* FOOD ADDITIONS START/' $file
        sed -i.bak 's/\/\* FOOD ADDITIONS END \*\//FOOD ADDITIONS END \*\//' $file
    done
    git checkout PetStoreSDK/Sources/PetStoreSDK/PetStoreSDKInfo.swift
fi

rm -rf $(find . -name '*.bak')

git status
