name: SkyTestFoundation
packages:
  Swifter:
    url: https://github.com/httpswift/swifter.git
    from: 1.5.0
options:
  bundleIdPrefix: it.sky
  deploymentTarget:
    iOS: "12.4"
targets:
  SkyTestFoundation:
    templates:
      - iOSFramework
    sources:
      - path: SkyTestFoundation
    settings:
        ENABLE_BITCODE: NO
    scheme:
      testTargets:
        - SkyTestFoundation-Tests
  SkyTestFoundation-Tests:
    templates:
      - iOSTestFramework
    sources:
      - SkyTestFoundationTests
    dependencies:
      - target: SkyTestFoundation
targetTemplates:
  iOSFramework:
    platform: iOS
    type: framework
    info:
      path: ${target_name}.plist
      properties:
        CFBundleIdentifier: it.sky.${target_name}
        CFBundleShortVersionString: "1.0.0"
    scheme:
      gatherCoverageData: true
    dependencies:
      - sdk: XCTest.framework
      - package: Swifter
  iOSTestFramework:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
