# Warning, do not change version.
version: 2.1

jobs:
  spm:
    macos:
      xcode: 12.2.0
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Enable cloning private Swift Package Manager repositories
          command: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run:
          name: Add GitHub to SSH Known Hosts
          command: |
            rm ~/.ssh/id_rsa || true
            for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run:
         name: Build & Test SPM Package
         command: >
           xcodebuild test
           -disableAutomaticPackageResolution
           -scheme SkyTestFoundation
           -destination 'platform=iOS Simulator,name=iPhone 11'
           | xcpretty
      - run:
         name: Run Demo iOS UI Test
         command: >
           xcodebuild test -disableAutomaticPackageResolution
           -project Demos/DemoIOS/DemoIOS.xcodeproj
           -scheme DemoIOSUITests
           -sdk iphonesimulator
           -destination 'platform=iOS Simulator,name=iPhone 11'
           -clonedSourcePackagesDirPath SourcePackages
workflows:
  version: 2
  build-test:
    jobs:
      - spm
