# Warning, do not change version.
version: 2.1

jobs:
  spm:
    macos:
      xcode: 12.5.1
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Enable cloning private Swift Package Manager repositories
          command: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run:
          name: Add GitHub to SSH Known Hosts
          command: |
            rm ~/.ssh/id_rsa || true
            for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run:
         name: Build & Test
         command: swift test
 
workflows:
  version: 2
  build-test:
    jobs:
      - spm
