# Warning, do not change version.
version: 2.1

jobs:
  prebase:
    macos:
      xcode: 12.0.0
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run:
         name: Build SkyTestFoundation
         command: >
           xcodebuild
           -disableAutomaticPackageResolution
           -scheme SkyTestFoundation
           -destination 'platform=iOS Simulator,name=iPhone 11'

workflows:
  version: 2
  build-test:
    jobs:
      - prebase
