
# Warning, do not change version.
version: 2
jobs:
# Swift setup
  build:
    macos:
      xcode: 11.7.0
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Build Framework
          command: xcodebuild | xcpretty

workflows:
  version: 2
  build-test:
    jobs:
      - build

