
# Warning, do not change version.
version: 2
aliases:
  - &boot_simulator
      name: Boot Simulator
      command: xcrun instruments -w "iPhone 11 (13.5) [" || true
  - &restore_gem_cache
      name: Restore Gemfile Cache
      key: 1-gems-{{ checksum "Gemfile.lock" }}
  - &bundle_install
      name: Update Gemfile
      command: bundle check || bundle install --path vendor/bundle
  - &save_gem_cache
      name: Save Gemfile Cache
      key: 1-gems-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - &restore_carthage_cache
      name: Restore Cartfile Cache
      key: 2-ca-{{ checksum "date" }}
  - &carthage_bootstrap
      name: Bootstrap iOS dependencies
      command: |
        curl https://gist.githubusercontent.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5/raw/4ba422e5f3a5e7e37cdcb1e232058c5431fc59fc/carthage-xc12.sh -o wcarthage && chmod +x wcarthage
        ./wcarthage bootstrap --platform ios --cache-builds
  - &save_carthage_cache
      name: Save Cartfile Cache
      key: 2-ca-{{ checksum "date" }}
      paths:
        - Carthage
  - &ruby_fix
      name: Set Ruby Version
      command:  echo "ruby-2.6" > ~/.ruby-version
  - &xcode_version
      xcode: 12.0.0

jobs:
  prebase:
    macos: *xcode_version
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: *ruby_fix
      - restore_cache: *restore_gem_cache
      - run: *bundle_install
      - save_cache: *save_gem_cache
      - run: date +%F > date
      - restore_cache: *restore_carthage_cache
      - run: *carthage_bootstrap
      - save_cache: *save_carthage_cache
      - persist_to_workspace:
          root: ~/
          paths: project

  run-unit-test:
    macos: *xcode_version
    shell: /bin/bash --login -eo pipefail
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Framework
          command: >
            xcodebuild test
            -scheme SkyTestFoundation
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11'
            | xcpretty

workflows:
  version: 2
  build-test:
    jobs:
      - prebase
      - run-unit-test:
          requires:
            - prebase

