//
// Pet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Pet: Codable, Hashable {

    public enum Status: String, Codable, Hashable, CaseIterable, CustomStringConvertible { 
        case available = "available"
        case pending = "pending"
        case sold = "sold"

        public var description: String {
            return rawValue
        }
    }

    public let _id: Int

    public let category: Category?

    public let name: String
    /** pet status in the store */
    public let status: Status?

    public init(_id: Int, category: Category? = nil, name: String, status: Status? = nil) { 
        self._id = _id
        self.category = category
        self.name = name
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case category
        case name
        case status
    }

}